Unit tests using real election results and data
albogdan/skule-vote pull request #179
Opened 2022-05-03 04:26 UTC by lisa-sa-li

## Overview

- Resolves #162
- A lot of finessing to make the .txt data match the format we needed

## Unit Tests Created

- <Briefly describe unit tests that were created>

## Steps to QA

- <Steps for a reviewer to QA your work>

2022-05-25 23:57 UTC, albogdan requested changes

2022-05-25 23:57 UTC, albogdan commented on skule_vote/backend/test_ballot_real_data.py
> +        with open("./backend/test_data/2022_Valedictoria.txt", "r") as f:
Change `valedictoria` to `valedictorian`

2022-05-25 23:57 UTC, albogdan commented on skule_vote/backend/test_data/2022_Valedictoria.txt
> +{
Rename file as well

2022-05-26 17:08 UTC, arminale approved these changes

2022-05-27 16:07 UTC, albogdan approved these changes

2022-05-27 16:08 UTC, merged